#define VULKAN_HPP_ASSERT_ON_RESULT //
#define VULKAN_HPP_NO_CONSTRUCTORS
#define VULKAN_HPP_NO_EXCEPTIONS
#define VULKAN_HPP_NO_NODISCARD_WARNINGS
#define VK_USE_PLATFORM_WAYLAND_KHR
#include <vulkan/vulkan.hpp>